### ISSUE TITLE
Beanstalkd persistence

### ISSUE THREAD

**Issue by NetoBraghetto** [jonbaldie/beanstalkd#1]
Hello Jonathan,
if i run the container with the flag -b, where do i find the [binlog](https://github.com/kr/beanstalkd/wiki/FAQ#are-the-jobs-persistent-what-happens-if-the-power-goes-out) file to backup?

**Comment by jonbaldie** [comment]
Hi Neto, the beanstalkd service is run through the default binary, so it *should* be wherever the default location is.

**Comment by jonbaldie** [comment]
Hi @NetoBraghetto, did you manage to find the location? I'd be interested in this information too. Then I can also close the issue.

**Comment by NetoBraghetto** [comment]
I couldn't access through /bin/bash to look for it, but i added this to my Dockerfile

```
RUN addgroup -S beanstalkd && adduser -S -G beanstalkd beanstalkd
RUN mkdir /data && chown beanstalkd:beanstalkd /data
VOLUME ["/data"]
EXPOSE 11300

ENTRYPOINT ["beanstalkd", "-p", "11300", "-u", "beanstalkd"]
CMD ["-b", "/data"]
```

**Comment by jonbaldie** [comment]
Ok thanks for that.
