### ISSUE TITLE
Don't run apk update

### ISSUE THREAD

**Issue by SamMousa** [jonbaldie/beanstalkd#2]
While the image is already amazingly small, there is no need to run `apk update`.

Instead if you use this command: `RUN apk add --no-cache beanstalkd` it'll work without creating a package cache.

**Comment by jonbaldie** [comment]
I like it. I'm currently atop a mountain in Spain so when I get back to my flat I'll have a closer look.

**Comment by jonbaldie** [comment]
Done with 70e9f.
