### ISSUE TITLE
Use entrypoint instead of cmd

### ISSUE THREAD

**Issue by SamMousa** [jonbaldie/beanstalkd#3]
Using the entrypoint has several benefits:
- No useless /bin/sh process.
- Easier configuration

It could then be run like this:
```sh
docker run jonbaldie/beanstalkd -b -p 12345
```

Note that this would break backwards compatibility since people already using a custom CMD will have their image broken...

**Comment by jonbaldie** [comment]
I like the concept but I'm reluctant given that it'll break backwards compatibility. Giving it a separate Docker tag in the Makefile would be a good compromise in my view.

**Comment by SamMousa** [comment]
I thought as much; I've decided to create a new image, free of bagage with respect to backwards compatibility.

https://hub.docker.com/r/marketflow/beanstalkd/
